
-- Ajouter les champs manquants spécifiques aux propriétaires dans la table leads
ALTER TABLE public.leads 
ADD COLUMN IF NOT EXISTS relationship_status text DEFAULT 'Nouveau contact',
ADD COLUMN IF NOT EXISTS mandate_type text,
ADD COLUMN IF NOT EXISTS specific_needs text,
ADD COLUMN IF NOT EXISTS attention_points text,
ADD COLUMN IF NOT EXISTS relationship_details text,
ADD COLUMN IF NOT EXISTS first_contact_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS last_contact_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS next_action_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS contact_source text,
ADD COLUMN IF NOT EXISTS internal_notes text,
ADD COLUMN IF NOT EXISTS property_description text,
ADD COLUMN IF NOT EXISTS property_state text,
ADD COLUMN IF NOT EXISTS construction_year text,
ADD COLUMN IF NOT EXISTS land_area text,
ADD COLUMN IF NOT EXISTS bathrooms integer,
ADD COLUMN IF NOT EXISTS assets text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS equipment text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS furnished boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS furniture_included_in_price boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS furniture_price text,
ADD COLUMN IF NOT EXISTS desired_price text,
ADD COLUMN IF NOT EXISTS fees text,
ADD COLUMN IF NOT EXISTS map_coordinates text;

-- Migrer les données existantes de la table owners vers leads
INSERT INTO public.leads (
    id, name, salutation, email, phone, nationality, preferred_language, 
    assigned_to, last_contacted_at, source, property_reference, url, 
    tags, regions, notes, internal_notes, action_history, task_type, 
    next_follow_up_date, integration_source, imported_at, external_id,
    desired_price, fees, currency, country, location, desired_location, 
    map_coordinates, property_type, bedrooms, bathrooms, living_area, 
    land_area, construction_year, property_state, property_description, 
    assets, equipment, furnished, furniture_included_in_price, furniture_price,
    status, specific_needs, attention_points, relationship_details,
    first_contact_date, last_contact_date, next_action_date, contact_source,
    relationship_status, mandate_type, pipeline_type, created_at
)
SELECT 
    id, full_name, salutation, email, phone, nationality, preferred_language,
    assigned_to, last_contacted_at, source, property_reference, url,
    tags, regions, notes, internal_notes, action_history, task_type,
    next_follow_up_date, integration_source, imported_at, external_id,
    desired_price, fees, currency, country, location, desired_location,
    map_coordinates, property_type, bedrooms, bathrooms, living_area,
    land_area, construction_year, property_state, property_description,
    assets, equipment, furnished, furniture_included_in_price, furniture_price,
    status, specific_needs, attention_points, relationship_details,
    first_contact_date, last_contact_date, next_action_date, contact_source,
    relationship_status, mandate_type, 'owners' as pipeline_type, created_at
FROM public.owners
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    salutation = EXCLUDED.salutation,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    nationality = EXCLUDED.nationality,
    preferred_language = EXCLUDED.preferred_language,
    assigned_to = EXCLUDED.assigned_to,
    last_contacted_at = EXCLUDED.last_contacted_at,
    source = EXCLUDED.source,
    property_reference = EXCLUDED.property_reference,
    url = EXCLUDED.url,
    tags = EXCLUDED.tags,
    regions = EXCLUDED.regions,
    notes = EXCLUDED.notes,
    internal_notes = EXCLUDED.internal_notes,
    action_history = EXCLUDED.action_history,
    task_type = EXCLUDED.task_type,
    next_follow_up_date = EXCLUDED.next_follow_up_date,
    integration_source = EXCLUDED.integration_source,
    imported_at = EXCLUDED.imported_at,
    external_id = EXCLUDED.external_id,
    desired_price = EXCLUDED.desired_price,
    fees = EXCLUDED.fees,
    currency = EXCLUDED.currency,
    country = EXCLUDED.country,
    location = EXCLUDED.location,
    desired_location = EXCLUDED.desired_location,
    map_coordinates = EXCLUDED.map_coordinates,
    property_type = EXCLUDED.property_type,
    bedrooms = EXCLUDED.bedrooms,
    bathrooms = EXCLUDED.bathrooms,
    living_area = EXCLUDED.living_area,
    land_area = EXCLUDED.land_area,
    construction_year = EXCLUDED.construction_year,
    property_state = EXCLUDED.property_state,
    property_description = EXCLUDED.property_description,
    assets = EXCLUDED.assets,
    equipment = EXCLUDED.equipment,
    furnished = EXCLUDED.furnished,
    furniture_included_in_price = EXCLUDED.furniture_included_in_price,
    furniture_price = EXCLUDED.furniture_price,
    status = EXCLUDED.status,
    specific_needs = EXCLUDED.specific_needs,
    attention_points = EXCLUDED.attention_points,
    relationship_details = EXCLUDED.relationship_details,
    first_contact_date = EXCLUDED.first_contact_date,
    last_contact_date = EXCLUDED.last_contact_date,
    next_action_date = EXCLUDED.next_action_date,
    contact_source = EXCLUDED.contact_source,
    relationship_status = EXCLUDED.relationship_status,
    mandate_type = EXCLUDED.mandate_type,
    pipeline_type = EXCLUDED.pipeline_type;

-- Supprimer la table owners après migration
DROP TABLE IF EXISTS public.owners CASCADE;
DROP TABLE IF EXISTS public.owner_actions CASCADE;
DROP TABLE IF EXISTS public.owner_properties CASCADE;
