
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxqoqkfnhbpwzkjgukrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4cW9xa2ZuaGJwd3pramd1a3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MjkyODMsImV4cCI6MjA1NzAwNTI4M30.lsQLzCFYTKVuViH3MM5Xk9j8Fx1h0dCS_rwxx9NXMbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log('Initialisation du client Supabase avec URL:', SUPABASE_URL);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Test d'initialisation
(async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    if (error) {
      console.error('Erreur lors de l\'initialisation de Supabase:', error);
    } else {
      console.log('Client Supabase initialisé avec succès. Session:', data.session ? 'Authentifié' : 'Non authentifié');
    }
  } catch (e) {
    console.error('Exception lors de l\'initialisation de Supabase:', e);
  }
})();
